# This is the workflow to have github talk to our IRC channels

name: IRC

on: 
  issues:
    types: [opened]
    branches: [ main ]

permissions:
  contents: read
  issues: read

jobs:
  notification:
    runs-on: self-hosted
    name: Notifications
    steps:
    - name: IRC notification
      uses: actions/issues@v2
      with:
        server: 'irc-2.devel.redhat.com'
        port: 6667
        channel: '##vdo-builds'
        nickname: bjohnston
        message: |-
          ${{ github.actor }} created an issue on github. This is a test.
