name: IRC

on: [issues]

jobs:
  notification:
    runs-on: ubuntu-latest
    name: Notifications
    steps:
    - name: IRC notification
      uses: Gottox/irc-message-action@v2
      with:
        channel: '#vdo-builds'
        server: irc-2.devel.redhat.com
        nickname: bjohnston
        message: |-
          ${{ github.actor }} created an issue on github.
