# This is the workflow to have github talk to our IRC channels

name: IRC

on: 
  issues:
    types: [opened]
    branches: [ main ]

permissions:
  contents: read
  issues: read

jobs:
  notification:
    runs-on: self-hosted
    steps:    
      - name: Notifications
        run: |
          cd ~/limnoria/runbot
          response = curl https://api.github.com/users/bjohnsto
