# This is the workflow to have github talk to our IRC channels

name: IRC

on: 
  issues:
    types: [opened, closed]
    branches: [ main ]
  pull_request:
    types: [opened, ready_for_review]
    branches: [ main ]
    
permissions:
  contents: read
  issues: read

jobs:
  notification:
    runs-on: self-hosted
    steps:    
      - name: Notifications
        run: |
          cd ~/brucebot
          echo "Sending ${{github.event_name}} event to webserver notifier"
          curl --verbose -X POST http://localhost:8080/github -H 'Content-Type: application/json' -H 'X-GitHub-Event: ${{github.event_name}}' -d @${{github.event_path}}
